/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 NICO ZAJIC*/
package programa;


import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;

/**
 *
 * @author diegoduro
 */
public class NuevoArticulo1 extends javax.swing.JFrame {

    /**
     * Creates new form nuevoArticulo
     */
    public NuevoArticulo1() {
        initComponents();
        la.llenarRubros(rubrosModel);
        
    }
    frmlistararticulos la = new frmlistararticulos();
    /*public void llenarRubros(){
          try {
            String sql="Select * from rubros r";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
         
            rubrosComboBox.setModel(rubrosModel);
           
            while (rs.next()){
              String cat = rs.getString("r.nombre"); 
              
                rubrosModel.addElement(cat);
                rubrosComboBox.setModel(rubrosModel); 
              }   
            
        } catch (SQLException ex) {
            Logger.getLogger(frmlistararticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    /*public int getRubro_id(String rubro) {
        int rubro_id = 0;   
        try {
            String selectId = "SELECT id FROM rubros WHERE nombre = '"+rubro+"';";
            Statement state = cn.createStatement();
            ResultSet rs1 = state.executeQuery(selectId);
            
            if (rs1.next()) {
               rubro_id = rs1.getInt(1);
            } else {
                
                System.out.println("NO SE ENCONTRO RUBRO");
            }
            
            
            } catch (SQLException ex) {
            Logger.getLogger(frmlistararticulos.class.getName()).log(Level.SEVERE, null, ex);
            }   
        
         return rubro_id;  
    }*/
    DefaultComboBoxModel rubrosModel = new DefaultComboBoxModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jPanel1 = new javax.swing.JPanel();
        lblRubroId1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JTextField();
        btnAgregar1 = new javax.swing.JButton();
        lblCantidad1 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JTextField();
        lblDescrip1 = new javax.swing.JLabel();
        txtDescrip1 = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        lblPrecio1 = new javax.swing.JLabel();
        rubrosComboBox = new javax.swing.JComboBox<>();

        lblRubroId1.setText("Rubro");

        lblNombre1.setText("Nombre ");

        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        lblCantidad1.setText("Cantidad");

        lblDescrip1.setText("Descripción");

        lblPrecio1.setText("Precio");

        rubrosComboBox.setModel(rubrosModel);
        rubrosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rubrosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescrip1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre1)
                            .addComponent(lblPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRubroId1))
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecio1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rubrosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDescrip1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(txtNombre1))
                            .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescrip1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescrip1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRubroId1)
                    .addComponent(rubrosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        try {
            String nombre = txtNombre1.getText();
            String descrip = txtDescrip1.getText();
            int cantidad = parseInt(txtCantidad1.getText());
            float precio = parseFloat(txtPrecio1.getText());
            int rubro_id = la.getRubro_id(rubrosModel.getSelectedItem().toString());
            
            String sql = "INSERT INTO articulos (nombre, desripcion, cantidad, precio, rubro_id, activo) VALUES ('"+nombre+"','"+descrip+"','"+cantidad+"','"+precio+"','"+rubro_id+"', 1);";
            Statement st = cn.createStatement();
            int rs = st.executeUpdate(sql);
            la.llenarTabla();
            this.setVisible(false);
            
        } catch (SQLException ex) {
            Logger.getLogger(NuevoArticulo1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void rubrosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubrosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rubrosComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblDescrip1;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblRubroId1;
    private java.awt.List list1;
    private javax.swing.JComboBox<String> rubrosComboBox;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtDescrip1;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPrecio1;
    // End of variables declaration//GEN-END:variables

  conectar cc = new conectar();
  Connection cn = cc.conexion();


}
